### ISSUE TITLE
Possible issue with supertest consuming response body as array

### ISSUE THREAD

**Issue by obsessiveprogrammer** [eljamaki01/NewsWatcherAWS#1]
In functional_api_crud.js, I'm getting failures on "News sharing and commenting operations" > "should return shared news story and comment".  When I run the tests manually using Postman, the results come back no problem, but during testing, storyID doesn't get set.  Could this be related to the fact that we are returning the body as an array, and the supertest response object does not understand "res.body[0]"?  This is the only thing I can think of.  Has the author or anyone else run into this same problem?

**Comment by eljamaki01** [comment]
I just ran those tests myself and they passed for me. The test right before it which is "should create a shared news story" shares a story with the post HTTP request. Then this next test you are mentioning does a get of the stories, and there should be at least one shared ta that point. You could try a console.log() in the test code to see what res.body is. console.log(res.body[0]) Or try running the node server from command line "node server.js" and then run the mocha test from vs code and set a breakpoint to inspect.

**Comment by obsessiveprogrammer** [comment]
Thanks for the quick response.  I'll give those suggestions a try.

**Comment by obsessiveprogrammer** [comment]
Got it figured out.  Typo'd something. :-)  Thanks for your help.
